### ISSUE TITLE
'cocon_block' has no attribute 'cocon_attn'

### ISSUE THREAD

**Issue by wying8349** [alvinchangw/COCON_ICLR2021#6]
We meet a problem like this:
Traceback (most recent call last):
  File "traininfer_cocon.py", line 2980, in <module>
    main()
  File "traininfer_cocon.py", line 2783, in main
    global_step, tr_loss = train_cocon(args, train_dataset, model, tokenizer, cocon_block=cocon_block, disc_model=disc_model, model_config=config, transform_h_after_layernorm=args.transform_h_after_layernorm)
  File "traininfer_cocon.py", line 573, in train_cocon
    self_cocon_lm_loss_grad = torch.autograd.grad(self_cocon_lm_loss, cocon_block.cocon_attn.c_attn.weight, retain_graph=True)[0]
  File "/home/yingwenjing/anaconda3/envs/cocon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'cocon_attn'

We sincerely look forward to your reply.

**Comment by GGG-c** [comment]
I have same question

**Comment by janleemark** [comment]
I have the same question when running "traininfer_cocon.py"
